# .travis.yml
addons:
  postgresql: "9.4"

before_script:
  - sudo apt-get remove postgresql postgresql-9.1 -qq --purge
  - sudo apt-get remove postgresql postgresql-9.2 -qq --purge
  - sudo apt-get remove postgresql postgresql-9.3 -qq --purge
#- sudo su $USER -c "source ./cfg/travis_cfg.sh && ./install-postgres"

script: sudo su $USER -c "env PGUSER=postgres DB=test ./runme integrate"
after_success: ./build/release.sh
